name: New plugin
description: Have a new plugin Idea? File it here
title: "[Plugin]: "
labels: ["plugin", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new plugin report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: idea
    attributes:
      label: What is your idea?
      description: Please be as specific as possible
      placeholder: Please tell us your idea!
      value: "I would like a plugin that ..."
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: What type of plugin should it be?
      options:
        - Menu
        - Editor
    validations:
      required: true
  - type: textarea
    id: mockups
    attributes:
      label: Relevant mockups
      description: If you have any mockups, please attach them here
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/openscd/.github/blob/main/profile/code_of_conduct.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
