on:
  workflow_dispatch:
    inputs:
      branch:
        description: Select branch
        required: true
        type: dynamic_branch
        default: main

  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
