# Triggers on all branches
on:
  push:
    branches:
       main


name: Sync Fork
jobs:
  release-please:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Create PR for Upstream
        uses: uknowwhoim/auto-pr-fork@v0.2
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
